FROM ubuntu:bionic

LABEL maintainer="morningspace@yahoo.com"

RUN apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
    vim inetutils-ping iproute2 curl rsyslog haproxy keepalived && \
    rm -rf /var/lib/apt/lists/*

COPY ./docker/init-lb.sh /
COPY ./conf/ssl /etc/ssl/
COPY ./conf/samples/haproxy /etc/haproxy
COPY ./conf/samples/keepalived /etc/keepalived

RUN chmod +x /init-lb.sh

ENTRYPOINT ["/init-lb.sh"]

CMD ["/bin/bash"]