FROM nginx

LABEL maintainer="morningspace@yahoo.com"

RUN apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
    vim && \
    rm -rf /var/lib/apt/lists/*

COPY ./docker/init-web.sh /
COPY ./conf/samples/nginx /etc/nginx/conf.d/
COPY ./conf/ssl /etc/ssl/

RUN chmod +x /init-web.sh

CMD ["/init-web.sh"]